name: deploy examen
on:
 push:
  branches: [ "main" ]

jobs:
 deploy:
  runs-on: self-hosted
  setps:
   - name: Deploy local
     shell: bash
     run:
       set -e
       cd /home/pau/Escritorio/PEC6/PEC_EX/ex/Ej3
       git pull origin main 
